### ISSUE TITLE
update request!

### ISSUE THREAD

**Issue by kubrastain** [shanapu/disarm#1]
The plugin is working perfectly as described.
I wonder if you can upgrade to not drop the player's knife, and if possible, show exactly the name of the weapon that was dropped.

PS: The non-drop of the knife, would be essential for a server to jailbreak: D

**Comment by shanapu** [comment]
So players keep the knife but all other weapons (incl grenates) will be removed?
I will add a cvar for that.

**Comment by shanapu** [comment]
https://github.com/shanapu/disarm/commit/29e1461704478138b5ca381083083483f0ce05fa
Here you go!   :)

The plugin doesn't create a own cfg file. you have to put `sm_disarm_knife "0"` into your gamemode_xxx.cfg or server.cfg
